### PR TITLE
minor fixes for KG scripts

### PR DESCRIPTION
**Pull request by abearab**
- [x] fill scripts missed from PR #207
- [x] fix and minor improvements in the `KnowledgeGraph` and `PrimeKGDev` classes
- [ ] write unit tests for `primekg` api

### CODE REVIEW

**Comment by abearab** [comment]
@amva13 This PR is ready for your review, thanks! It mostly contains minor fixes missed in #207

**Comment by amva13** [comment]
Hi @abearab wpuld yoh like to write unit tests for Primekg api? If so and they pass we can approve your changes to main primekg class.

Otherwise, I'll approve primekgdev soon.

A

**Comment by abearab** [comment]
Hi @amva13, I'll be happy to write unit tests and replace primekgdev with Primekg api.

**Comment by amva13** [comment]
Ok great. You can make the changes in this PR and I'll review.

**Pull request merged**
