### PR TITLE
New TCR-Epitope Binding Affinity Prediction Task

### LINKED ISSUE #129: New TCR-Epitope Binding Affinity Prediction Task
**Describe the problem**
T-cells are an integral part of the adaptive immune system, whose survival, proliferation, activation and function are all governed by the interaction of their T-cell receptor (TCR) with immunogenic peptides (epitopes). A large repertoire of T-cell receptors with different specificity is needed to provide protection against a wide range of pathogens. This new task aims to predict the binding affinity given a pair of TCR sequence and epitope sequence. 

**Describe the solution you'd like**

```python
from tdc.multi_pred import TCR_Epitope_Binding
data = TCR_Epitope_Binding(name = 'Weber',  path = './data')
```

**Additional context**
Reference: https://academic.oup.com/bioinformatics/article/37/Supplement_1/i237/6319659 
Data folder: https://ibm.ent.box.com/v/titan-dataset

### PR DESCRIPTION
**Pull request by annaweber209**
fixes #129. 

The new TCR-Epitope Binding Affinity Prediction Task can be used via: 

`from tdc.multi_pred import TCREpitopeBinding
data = TCREpitopeBinding(name = 'weber',  path = './data')`
 
The 'weber' dataset contains information about TCR full and cdr3 sequence, as well as epitope sequence as amino acids or smiles strings.

### CODE REVIEW

**Comment by kexinhuang12345** [comment]
Thanks, Anna! It works perfectly! Could you also provide some more information about the task and dataset? We would like to highlight it on the website. An example would be https://tdcommons.ai/multi_pred_tasks/peptidemhc/

Particularly, for the task, it would be definition/impact/generalization/product/pipeline. And for the dataset, it would be dataset  description/task description/dataset statistics/recommended splits/reference/license. 

Any written draft would be great! If you are busy, let us know, we can also come up with something : )

**Review by kexinhuang12345 — APPROVED** [review]

**Comment by kexinhuang12345** [comment]
Hi @annaweber209 and @jannisborn i drafted the following text on the TDC website for this task. Could you guys double check to see if you want to edit anything? thanks!!

----

Description: T-cells are an integral part of the adaptive immune system, whose survival, proliferation, activation and function are all governed by the interaction of their T-cell receptor (TCR) with immunogenic peptides (epitopes). A large repertoire of T-cell receptors with different specificity is needed to provide protection against a wide range of pathogens. This new task aims to predict the binding affinity given a pair of TCR sequence and epitope sequence.

Impact: An accurate model can help design TCR receptor for effective immunotherapy. It can also unlock a patients’ TCR repertoire, which reflects their immune history and could inform about past and current infectious diseases, vaccine effectiveness or autoimmune reactions.

Generalization: The models are expected to be generalized to unseen TCR-epitope pairs and also generalize to epitope that is never-before-seen. 

Product: Immunotherapy. 

Pipeline: Activity.

Dataset description: The dataset is from Weber et al. who assemble a large and diverse data from the VDJ database and ImmuneCODE project. It uses all human TCR-beta chain sequences. Since this dataset is highly imbalanced, the authors exclude epitopes with less than 15 associated TCR sequences and downsample to a limit of 400 TCRs per epitope. The dataset contains amino acid and SMILES representation for epitope and the amino acid full sequence of CDR3 region sequence for TCR.

Dataset Statistics: 47,182 TCR-Epitope pairs between 192 epitopes and 23,139 TCRs. 

Dataset Split: Random Split, Cold Epitope Split

```python
from tdc.multi_pred import TCREpitopeBinding 
data = TCREpitopeBinding(name = 'weber', path = './data')
split = data.get_split()
```

References:
[1] [Weber, Anna, Jannis Born, and María Rodriguez Martínez. "TITAN: T-cell receptor specificity prediction with bimodal attention networks." Bioinformatics 37.Supplement_1 (2021): i237-i244.](https://academic.oup.com/bioinformatics/article-abstract/37/Supplement_1/i237/6319659)

[2] [Bagaev, Dmitry V., et al. "VDJdb in 2019: database extension, new analysis infrastructure and a T-cell receptor motif compendium." Nucleic Acids Research 48.D1 (2020): D1057-D1062.](https://academic.oup.com/nar/article-abstract/48/D1/D1057/5582255)

[3] [Dines, Jennifer N., et al. "The immunerace study: A prospective multicohort study of immune response action to covid-19 events with the immunecode™ open access database." medRxiv (2020).](https://www.medrxiv.org/content/10.1101/2020.08.17.20175158.abstract)

**Comment by jannisborn** [comment]
Hi @kexinhuang12345, thanks a lot for doing this. I think it's great, here are few comments:



_Dataset Split: Cold TCR Split, Cold TCR/Epitope Split_

Comment:The Random split will be too easy to solve. In our paper, we use a Cold TCR split and a Cold TCR-Epitope split; where we split by both modalities together. Cold Epitope split alone might also be very useful since the generalization toward new epitopes is the grand challenge.

_Generalization: The models are, at very least, expected to generalize to unseen TCRs. But the main challenge of this dataset is to generalize to samples where both epitope and TCR are unseen._

Also I would replace this sentence 
> The dataset contains amino acid and SMILES representation for epitope and the amino acid full sequence of CDR3 region sequence for TCR.

with

_The dataset contains amino acid sequences either for the entire TCR or only for the hypervariable CDR3 loop. Epitopes are available as amino acid sequences. Since Weber et al. proposed to represent the peptides as SMILES strings (which reformulates the problem to protein-ligand binding prediction) the SMILES strings of the epitopes are also included._

Maybe @annaweber209 has some more thoughts?

**Comment by kexinhuang12345** [comment]
Great! Thanks for the feedback! @annaweber209 let me know if there is any additional thought!

**Comment by annaweber209** [comment]
Sorry for the late reply @kexinhuang12345 ! 

I would add a sentence to the dataset description saying: "_50% negative samples were generated by shuffling the pairs, i.e. associating TCR sequences with epitopes they have not been shown to bind._"

Another small comment is to remove the word "all" from "_It uses all human TCR-beta chain sequences."_ since we excluded some of the TCR sequences during the downsampling process.

**Comment by kexinhuang12345** [comment]
Awesome! Thanks so much! It is included on the [website](https://tdcommons.ai/multi_pred_tasks/tcrepitope/) and we will be alive in 0.3.6, scheduled to be released this weekend. let us know if you have any questions before then!

**Pull request merged**
