### PR TITLE
[0.14.17] Loosen requirements with bounds

### PR DESCRIPTION
**Pull request by malcolmgreaves**
Loosens the requirements by establishing the current `==` as lower bounds (`>=`) and uses the next major version update as an upper bound (`<`).

Bumps patch version to `0.4.17` too.

### CODE REVIEW

**Comment by malcolmgreaves** [comment]
Hello! 👋 

This PR enables downstream users to have greater compatibility with TDC's dependencies. Currently, it is difficult to use TDC as a dependency since its dependencies are pinned to specific versions. This PR allows for more flexibility by enabling any non breaking change version of a dependency to be used.

**Comment by malcolmgreaves** [comment]
@amva13 Not sure if you'd like me to include the version bump in this PR or not. Happy to make any changes :)

**Comment by amva13** [comment]
@malcolmgreaves, sorry for the delay. will review it in the next few days. TDC is submitting a paper.

Skimming it looks reasonable

**Comment by malcolmgreaves** [comment]
No worries! Thanks for taking a look. Good luck on the submission 🤞

**Comment by amva13** [comment]
hi @malcolmgreaves this is merged and new version released. Let me know if you still face any issues!

https://pypi.org/project/PyTDC/0.4.17/

**Comment by malcolmgreaves** [comment]
Thank you very much! 👏 I'll try it out today!

**Comment by cye-nvidia** [comment]
As a corollary to this MR, would bit be possible to completely relax the version requirement for `pandas`? I don't think anything in this repo requires `pandas>=2.1.4` right?

Pandas has had rapid growth recently and our production containers aren't keeping up... we're living in `pandas==1.5.3` right now and depend on PyTDC.

**Pull request merged**
